version: '3'
services:
  kelon:
    build: .
    restart: always
    depends_on:
      - mysql
      - postgres
    ports:
      - "8181:8181"
      - "9191:9191"
    volumes:
      - ./examples/config/:/conf
      - ./call-operands/:/call-operands
    environment:
      - DATASTORE_CONF=/conf/datastore.yml
      - API_CONF=/conf/api.yml
      - OPA_CONF=/conf/opa.yml
      - REGO_DIR=/conf

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'appstore'
      MYSQL_USER: 'You'
      MYSQL_PASSWORD: 'SuperSecure'
      MYSQL_ROOT_PASSWORD: 'root-beats-everything'
    ports:
      - '3306:3306'
    volumes:
      - ./examples/init/Init-MySql.sql:/docker-entrypoint-initdb.d/Init-MySql.sql

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'appstore'
      POSTGRES_USER: 'You'
      POSTGRES_PASSWORD: 'SuperSecure'
    ports:
      - '5432:5432'
    volumes:
      - ./examples/init/Init-Postgres.sql:/docker-entrypoint-initdb.d/Init-Postgres.sql

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017-27019:27017-27019"
    environment:
      MONGO_INITDB_ROOT_USERNAME: Root
      MONGO_INITDB_ROOT_PASSWORD: RootPwd
      MONGO_INITDB_DATABASE: appstore
    volumes:
      - ./examples/init/Init-Mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080