version: '3'
services:
  kelon:
    build: .
    ports:
      - "8181:8181"
    volumes:
      - ./examples/config/:/conf
    environment:
      - DATASTORE_CONF=/conf/datastore.yml
      - API_CONF=/conf/api.yml
      - OPA_CONF=/conf/opa.yml
      - REGO_PATHS=/conf/example.rego