apis:
  - path-prefix: /api/v1
    datastore: mysql
    mappings:
      - path: /apps.*
        package: applications
      - path: /apps/[\d]+
        package: applications
      - path: /apps/[\d]+
        package: applications
        methods:
          - GET
