# Datastores to connect to
datastores:
  postgres:
    type: postgres
    connection:
      host: "localhost"
      port: 5432
      database: postgres
      user: postgres
      password: SuperSecure
    metadata:
      default_schema: default
  local-json:
    type: file
    connection:
      location: ./data/local-data.json
    metadata:
      in_memory: true

# Entity-Schemas define the structure of the entities of one schema inside a datastore
entity_schemas:
  postgres:                             # Target datastore
    appstore:                           # Target schema              
      entities:                         # List of all entities of the schema
        - users
        - followers
        - app_rights
        - apps
        - app_tags
        - tags
      links:                            # Link an entity's column to a set of other entities
        users:                          # Table users
          - column: id                  # Column id
            link:                       
              followers:                # Has foreign key constraint on table: [followers], column: [user_id]
                column: user_id         # Resulting join would be: SELECT * FROM <schema>.users u
              app_rights:               #                                JOIN <schema>.followers f ON u.id == f.user_id
                column: user_id
              tags:
                column: creator
              apps:
                column: owner
        apps:
          - column: id
            link:
              app_rights:
                column: app_id
              app_tags:
                column: app_id
        tags:
          - column: id
            link:
              app_tags:
                column: tag_id
