# handler for adapter kelonistioadapter
apiVersion: "config.istio.io/v1alpha2"
kind: handler
metadata:
  name: h1
  namespace: istio-system
spec:
  adapter: kelonistioadapter
  connection:
    address: "{ADDRESS}" #replaces at runtime by the test
---

# instance for template authorization
apiVersion: "config.istio.io/v1alpha2"
kind: instance
metadata:
  name: i1authorization
  namespace: istio-system
spec:
  template: authorization
  params:
    value: request.size | 0
    dimensions:
      response_code: "200"
---

# rule to dispatch to handler h1
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: r1
  namespace: istio-system
spec:
  actions:
    - handler: h1.istio-system
      instances:
        - i1authorization
---