apis:
  # Route all requests starting with /api/mysql to mysql database
  - path-prefix: /api/mysql
    datastores:
      - mysql
    mappings:
      - path: /apps/.*                   # Matches [GET,POST,PUT,DELETE,PATCH] /api/mysql/apps/.*
        package: applications.mysql
      - path: /apps/[\d]+               # Matches [GET,POST,PUT,DELETE,PATCH] /api/mysql/apps/[\d]+
        package: applications.mysql
      - path: /apps/[\d]+               # Only matches GET /api/mysql/apps/[\d]+
        package: applications.mysql
        methods:
          - GET
      - path: /.*
        package: test
  # Route all requests starting with /api/mongo to MongoDB
  - path-prefix: /api/mongo
    datastores:
      - mongo
    mappings:
      - path: /apps/.*
        package: applications.mongo
  # Route all requests staring with /api/pure to no Datastore without authentication
  - path-prefix: /api/pure
    authentication: false
    mappings:
      - path: /apps/.*
        package: applications.pure
  # Route all requests starting with /api/mixed to MongoDB and Postgres
  - path-prefix: /api/mixed
    datastores:
      - mongo
      - pg
    authentication: false
    mappings:
      - path: /apps/.*
        package: applications.mixed
  # Route all requests staring with /api/spice to no Datastore without authentication
  - path-prefix: /api/spice
    datastores:
      - mysql
    mappings:
      - path: /apps/.*
        package: applications.spice
  # All other requests are routed to postgres
  - path-prefix: /api/.*?
    datastores:
      - pg
    mappings:
      - path: /apps/.*
        package: applications.pg