# Datastores to connect to
datastores:
  mysql:
    type: mysql
    connection:
      host: mysql
      port: 3306
      database: appstore
      user: You
      password: SuperSecure
    metadata:
      maxIdleConnections: 5
      maxOpenConnections: 10
      connectionMaxLifetimeSeconds: 1800
      telemetryName: Datasource
      telemetryType: MySQL

  pg:
    type: postgres
    connection:
      host: postgres
      port: 5432
      database: appstore
      user: You
      password: SuperSecure
      sslmode: disable
    metadata:
      maxIdleConnections: 5
      maxOpenConnections: 10
      connectionMaxLifetimeSeconds: 1800
      telemetryName: Datasource
      telemetryType: PostgreSQL

  mongo:
    type: mongo
    connection:
      host: mongo
      port: 27017
      database: appstore
      user: You
      password: SuperSecure
    metadata:
      telemetryName: Datasource
      telemetryType: MongoDB

  spice:
    type: spicedb
    connection:
      host: spicedb
      port: 50051
      insecure: true
      token: spicykelon

# Entity-Schemas define the structure of the entities of one schema inside a datastore
entity_schemas:

  mysql:                                # Target datastore
    appstore:                           # Target schema
      entities:                         # List of all entities of the schema
        - name: users
        - name: app_rights
        - name: apps
        - name: app_tags
        - name: tags

  pg:
    appstore:
      entities:
        - name: users
          alias: pg_users
        - name: app_rights
          alias: pg_app_rights
        - name: apps
          alias: pg_apps
        - name: app_tags
          alias: pg_app_tags
        - name: tags
          alias: pg_tags

  mongo:
    appstore:
      entities:
        - name: users
        - name: apps
          entities:
            - name: rights
              entities:
                - name: user
                  alias: users