name: Build & Publish
on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Install golangci-lint
        run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.24.0

      - name: Run golangci-lint
        run: $(go env GOPATH)/bin/golangci-lint run -c .golangci.yml --timeout=5m

  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.12

      - name: Check out code
        uses: actions/setup-go@v2

      - name: Run Unit tests.
        run: make test-coverage

  scan:
    name: Scan
    runs-on: ubuntu-20.04
    needs: [lint, test]
    steps:
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ${{ secrets.GITHUB_WORKSPACE }}

  build:
    name: Build
    if: ${{ !github.base_ref }}
    runs-on: ubuntu-20.04
    needs: [lint, test]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.12

      - name: Check out code
        uses: actions/setup-go@v2

      - name: Build
        run: make build

  publish:
    name: Publish
    if: ${{ !github.base_ref }}
    runs-on: ubuntu-20.04
    needs: [lint, test, build]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.12

      - name: Check out code
        uses: actions/setup-go@v2

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build latest container image
        run: docker build -t kelonio/kelon:${{ github.sha }} -t kelonio/kelon:latest .
        if: ${{ endsWith(github.ref, 'develop') }}

      - name: Build stable container image
        run: docker build -t kelonio/kelon:${{ github.sha }} -t kelonio/kelon:stable .
        if: ${{ endsWith(github.ref, 'master') }}

      - name: Run Trivy vulnerability scanner
        if: ${{ !github.base_ref }}
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'kelonio/kelon:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        if: ${{ !github.base_ref }}
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Push latest images to DockerHub
        run: echo kelonio/kelon:${{ github.sha }} kelonio/kelon:latest | xargs -n 1 docker push
        if: ${{ endsWith(github.ref, 'develop') }}

      - name: Push stable images to DockerHub
        run: echo kelonio/kelon:${{ github.sha }} kelonio/kelon:stable | xargs -n 1 docker push
        if: ${{ endsWith(github.ref, 'master') }}