name: Build and Test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Run GolangCI-Lint Action by building from repository
        uses: matoous/golangci-lint-action@v1.1.0
        with:
          config: .golangci.yml

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.12

      - name: Check out code
        uses: actions/checkout@v1

      - name: Run Unit tests.
        run: make test-coverage

          #- name: Upload Coverage report to CodeCov
          #  uses: codecov/codecov-action@v1.0.0
          #  with:
          #    token: ${{secrets.CODECOV_TOKEN}}
          #    file: ./coverage.txt

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.12

      - name: Check out code
        uses: actions/checkout@v1

      - name: Build
        run: make build

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [lint, test, build]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.12

      - name: Check out code
        uses: actions/checkout@v1

      - name: Login to Registry
        run: docker login docker.pkg.github.com -u ${{ secrets.PACKAGE_USERNAME }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        run: docker login hub.docker.com -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build container image
        run: docker build -t docker.pkg.github.com/foundato/kelon/kelon:$(git rev-parse --short HEAD) -t kelonio/kelon:$(git rev-parse --short HEAD) -t kelonio/kelon:latest .

      - name: Push image to github packages
        run: docker push docker.pkg.github.com/foundato/kelon/kelon:$(git rev-parse --short HEAD)

      - name: Push images to DockerHub
        run: echo kelonio/kelon:$(git rev-parse --short HEAD) kelonio/kelon:latest | xargs -n 1 docker push